# Generated by Django 3.0.2 on 2020-01-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200107_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['reference']},
        ),
        migrations.RenameField(
            model_name='publication',
            old_name='genre',
            new_name='isbn',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='type',
        ),
        migrations.AddField(
            model_name='publication',
            name='type_publication',
            field=models.CharField(choices=[('_', 'Livres'), ('O', 'Autres'), ('M', 'Musique'), ('F', 'Films')], default='_', max_length=1),
        ),
        migrations.AlterField(
            model_name='dewey',
            name='number',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='publication',
            name='reference',
            field=models.CharField(editable=False, max_length=61),
        ),
    ]
