# Generated by Django 3.0.2 on 2020-01-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200108_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='century_birth',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
