# Generated by Django 3.0.2 on 2020-01-09 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20200109_1010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dewey',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='dewey',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
