# Generated by Django 3.0.2 on 2020-01-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20200109_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewey',
            name='bg_color',
            field=models.CharField(default='*', editable=False, max_length=7),
        ),
        migrations.AlterField(
            model_name='dewey',
            name='text_color',
            field=models.CharField(default='*', editable=False, max_length=7),
        ),
    ]
