# Generated by Django 3.0.2 on 2020-01-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_auto_20200109_1231'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name'], 'verbose_name': 'Auteur'},
        ),
        migrations.AlterModelOptions(
            name='dewey',
            options={'ordering': ['number'], 'verbose_name': 'Numéros Dewey'},
        ),
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ['reference'], 'verbose_name': 'Publication'},
        ),
        migrations.AlterField(
            model_name='dewey',
            name='name',
            field=models.CharField(max_length=61, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='dewey',
            name='number',
            field=models.CharField(max_length=12, verbose_name='Numéro'),
        ),
    ]
