# Generated by Django 3.0.2 on 2020-01-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20200123_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
